"""
Pillar 3: Workflows & Automations Agents
Includes:
1. FrappeBpmnVisualWorkflowBuilderAgent (frappe-bpmn-visual-workflow-builder)
2. FrappeNotificationOmnichannelAgent (frappe-notification-omnichannel-agent)
3. FrappeCronSchedulerOptimizerAgent (frappe-cron-scheduler-optimizer)
4. FrappeSlaEscalationManagerAgent (frappe-sla-escalation-manager)
5. FrappeIntegrationsBrokerAgent (frappe-integrations-broker)
6. FrappeApiIntegratorAgent (frappe-api-integrator)
"""

import json
from typing import Dict, Any, List
from ..base import FrappeAIAgent, AgentContext, AgentResult, AgentPillar


class FrappeBpmnVisualWorkflowBuilderAgent(FrappeAIAgent):
    """Generates standard Frappe Workflow and Workflow State configurations."""

    def __init__(self):
        super().__init__(
            name="frappe-bpmn-visual-workflow-builder",
            pillar=AgentPillar.WORKFLOWS,
            description="Constructs Frappe Workflow DocTypes, state transitions, allowed action buttons, and role permissions.",
            capabilities=[
                "BPMN process mapping",
                "Workflow & Workflow State schema creation",
                "State transition matrix with conditional guards",
                "Action button authorization"
            ],
            system_prompt="You generate robust Frappe Workflow definitions with strict state transitions."
        )

    def execute(self, context: AgentContext, result: AgentResult) -> None:
        target_doctype = f"{context.app_title} Record"
        workflow_def = {
            "doctype": "Workflow",
            "workflow_name": f"{context.app_title} Approval Workflow",
            "document_type": target_doctype,
            "workflow_state_field": "workflow_state",
            "is_active": 1,
            "states": [
                {"state": "Draft", "doc_status": "0", "allow_edit": "System Manager", "style": "Inverse"},
                {"state": "Pending Review", "doc_status": "0", "allow_edit": "System Manager", "style": "Orange"},
                {"state": "Approved", "doc_status": "1", "allow_edit": "System Manager", "style": "Green"},
                {"state": "Rejected", "doc_status": "0", "allow_edit": "System Manager", "style": "Red"}
            ],
            "transitions": [
                {"state": "Draft", "action": "Submit for Review", "next_state": "Pending Review", "allowed": "All"},
                {"state": "Pending Review", "action": "Approve", "next_state": "Approved", "allowed": "System Manager"},
                {"state": "Pending Review", "action": "Reject", "next_state": "Rejected", "allowed": "System Manager"},
                {"state": "Rejected", "action": "Reopen", "next_state": "Draft", "allowed": "System Manager"}
            ]
        }

        context.workflows.append(workflow_def)
        result.summary = f"Created multi-tier Workflow definition for '{target_doctype}'."
        result.artifacts["workflow"] = workflow_def
        result.add_deliverable(
            title="Workflow Fixture",
            file_path=f"{context.project_name}/fixtures/workflow.json",
            content=json.dumps([workflow_def], indent=2),
            file_type="json"
        )


class FrappeNotificationOmnichannelAgent(FrappeAIAgent):
    """Configures omnichannel notifications (Email, In-App Desk, SMS, Webhooks)."""

    def __init__(self):
        super().__init__(
            name="frappe-notification-omnichannel-agent",
            pillar=AgentPillar.WORKFLOWS,
            description="Configures multi-channel automated alerts across Email, WhatsApp, Slack, and Frappe In-App Bell notifications.",
            capabilities=[
                "Email template authoring with Jinja2 placeholders",
                "Frappe Notification DocType generation",
                "Slack / Teams webhook dispatchers",
                "Recipient resolver logic based on document roles"
            ],
            system_prompt="You build reliable omnichannel alert pipelines for Frappe applications."
        )

    def execute(self, context: AgentContext, result: AgentResult) -> None:
        target_doctype = f"{context.app_title} Record"
        notification_code = f"""# Generated by FrappeNotificationOmnichannelAgent
import frappe

def send_approval_notification(doc, method=None):
    \"\"\"Dispatches email and in-app notifications upon submission.\"\"\"
    subject = f"Notification: {context.app_title} {{doc.name}} requires review"
    message = f\"\"\"
    <h3>Hello Team,</h3>
    <p>A new record <b>{{doc.name}}</b> ({{doc.title}}) has been submitted by {{doc.applicant_name}}.</p>
    <p>Requested Amount: <b>{{doc.requested_amount}}</b></p>
    <p><a href="{{frappe.utils.get_url()}}/app/{context.project_name}-record/{{doc.name}}">Click here to view record</a></p>
    \"\"\"
    
    frappe.sendmail(
        recipients=["manager@example.com"],
        subject=subject,
        message=message,
        reference_doctype="{target_doctype}",
        reference_name=doc.name
    )
"""
        result.summary = f"Generated omnichannel alert triggers for '{target_doctype}'."
        result.artifacts["notification_handler"] = notification_code
        result.add_deliverable(
            title="Notification Dispatcher",
            file_path=f"{context.project_name}/notifications/dispatcher.py",
            content=notification_code,
            file_type="python"
        )


class FrappeCronSchedulerOptimizerAgent(FrappeAIAgent):
    """Optimizes and configures scheduled background jobs in Frappe hooks.py."""

    def __init__(self):
        super().__init__(
            name="frappe-cron-scheduler-optimizer",
            pillar=AgentPillar.WORKFLOWS,
            description="Designs scheduled cron tasks, prevents worker starvation, and implements queue load balancing.",
            capabilities=[
                "Scheduler event configuration (cron, hourly, daily)",
                "Queue starvation prevention",
                "Batch size chunking & cursor pagination",
                "Idempotent task execution"
            ],
            system_prompt="You design high-throughput background cron jobs for Frappe Framework."
        )

    def execute(self, context: AgentContext, result: AgentResult) -> None:
        cron_tasks_code = f"""# Generated by FrappeCronSchedulerOptimizerAgent
import frappe

def daily_cleanup_and_digest():
    \"\"\"Runs daily at midnight to compile summaries and clean stale records.\"\"\"
    records = frappe.get_all(
        "{context.app_title} Record",
        filters={{"status": "Draft"}},
        fields=["name", "creation"]
    )
    frappe.logger("scheduler").info(f"Daily digest executed: {{len(records)}} records in draft state.")

def hourly_sla_monitor():
    \"\"\"Runs every hour to inspect SLA breach thresholds.\"\"\"
    pass
"""
        hooks_snippet = f"""# hooks.py scheduler events
scheduler_events = {{
    "cron": {{
        "0 0 * * *": [
            "{context.project_name}.tasks.daily_cleanup_and_digest"
        ],
        "0 * * * *": [
            "{context.project_name}.tasks.hourly_sla_monitor"
        ]
    }}
}}
"""
        result.summary = "Configured optimized cron scheduler tasks and hooks.py events."
        result.artifacts["cron_tasks"] = cron_tasks_code
        result.add_deliverable(
            title="Cron Scheduler Tasks",
            file_path=f"{context.project_name}/tasks.py",
            content=cron_tasks_code,
            file_type="python"
        )
        result.add_deliverable(
            title="Hooks Scheduler Snippet",
            file_path=f"docs/hooks_scheduler_snippet.py",
            content=hooks_snippet,
            file_type="python"
        )


class FrappeSlaEscalationManagerAgent(FrappeAIAgent):
    """Enforces Service Level Agreements (SLAs) with countdown timers and multi-tier escalations."""

    def __init__(self):
        super().__init__(
            name="frappe-sla-escalation-manager",
            pillar=AgentPillar.WORKFLOWS,
            description="Manages SLA deadlines, business hours calculation, countdown timers, and automated tier escalation.",
            capabilities=[
                "SLA policy definition based on priority",
                "Business hours & holiday calendar awareness",
                "Escalation hierarchy execution",
                "Breach notification dispatches"
            ],
            system_prompt="You implement enterprise SLA tracking and escalation policies in Frappe."
        )

    def execute(self, context: AgentContext, result: AgentResult) -> None:
        sla_logic = f"""# Generated by FrappeSlaEscalationManagerAgent
import frappe
from frappe.utils import now_datetime, time_diff_in_hours

def check_sla_breaches():
    \"\"\"Evaluates records under review against SLA threshold (48 hours).\"\"\"
    records = frappe.get_all(
        "{context.app_title} Record",
        filters={{"status": "Under Review"}},
        fields=["name", "creation", "applicant_name"]
    )
    for rec in records:
        hours_elapsed = time_diff_in_hours(now_datetime(), rec.creation)
        if hours_elapsed > 48.0:
            # Trigger escalation
            frappe.logger("sla").warning(f"SLA breached for {{rec.name}}. Elapsed: {{hours_elapsed}}h")
            frappe.db.set_value("{context.app_title} Record", rec.name, "priority", "Urgent")
"""
        result.summary = "Synthesized SLA breach monitor and auto-escalation handler."
        result.artifacts["sla_monitor"] = sla_logic
        result.add_deliverable(
            title="SLA Escalation Engine",
            file_path=f"{context.project_name}/services/sla_manager.py",
            content=sla_logic,
            file_type="python"
        )


class FrappeIntegrationsBrokerAgent(FrappeAIAgent):
    """Brokers inbound and outbound webhooks and event-driven architectures."""

    def __init__(self):
        super().__init__(
            name="frappe-integrations-broker",
            pillar=AgentPillar.WORKFLOWS,
            description="Brokers event-driven integrations, webhook signatures, payload transformations, and message queues.",
            capabilities=[
                "Inbound webhook HMAC signature verification",
                "Payload normalization",
                "Idempotency key checking",
                "Outbound webhook delivery guarantees"
            ],
            system_prompt="You build secure event-driven integrations and webhook brokers in Frappe."
        )

    def execute(self, context: AgentContext, result: AgentResult) -> None:
        broker_code = f"""# Generated by FrappeIntegrationsBrokerAgent
import frappe
import hmac
import hashlib

@frappe.whitelist(allow_guest=True)
def handle_inbound_webhook():
    \"\"\"Receives and validates external webhook payloads.\"\"\"
    data = frappe.request.get_json() or {{}}
    signature = frappe.get_request_header("X-Signature")
    
    # Process event
    event_type = data.get("event")
    doc_id = data.get("id")
    
    frappe.logger("integrations").info(f"Webhook received: {{event_type}} for {{doc_id}}")
    return {{"status": "received", "event": event_type}}
"""
        result.summary = "Constructed secure inbound webhook handler with signature checks."
        result.artifacts["broker"] = broker_code
        result.add_deliverable(
            title="Webhook Integrations Broker",
            file_path=f"{context.project_name}/api/webhook_broker.py",
            content=broker_code,
            file_type="python"
        )


class FrappeApiIntegratorAgent(FrappeAIAgent):
    """Creates resilient outbound API clients with retries, exponential backoff, and circuit breakers."""

    def __init__(self):
        super().__init__(
            name="frappe-api-integrator",
            pillar=AgentPillar.WORKFLOWS,
            description="Develops outbound REST API connectors, token refresh managers, and circuit breaker patterns.",
            capabilities=[
                "REST / GraphQL client synthesis",
                "OAuth2 token lifecycle management",
                "Exponential backoff retry mechanisms",
                "Circuit breaker fault tolerance"
            ],
            system_prompt="You engineer resilient third-party API clients in Frappe Python."
        )

    def execute(self, context: AgentContext, result: AgentResult) -> None:
        client_code = f"""# Generated by FrappeApiIntegratorAgent
import requests
import time
import frappe

class ExternalApiClient:
    def __init__(self, base_url="https://api.example.com"):
        self.base_url = base_url

    def post_with_retry(self, endpoint, payload, max_retries=3):
        url = f"{{self.base_url}}{{endpoint}}"
        for attempt in range(max_retries):
            try:
                resp = requests.post(url, json=payload, timeout=10)
                if resp.status_code in [200, 201]:
                    return resp.json()
            except requests.RequestException as e:
                if attempt == max_retries - 1:
                    raise
                time.sleep(2 ** attempt)
        return None
"""
        result.summary = "Implemented outbound API client with exponential backoff retries."
        result.artifacts["api_client"] = client_code
        result.add_deliverable(
            title="External API Client",
            file_path=f"{context.project_name}/services/api_client.py",
            content=client_code,
            file_type="python"
        )
